active: "testnet"

mainnet:
  node: 
    rpc_node: "tcp://47.95.203.106:26657" # tcp://dataseed1.binance.org:80
    api_server_endpoint: "http://47.95.203.106:8545"

testnet:
  node:
#    rpc_node: "tcp://127.0.0.1:26657"
    rpc_node: "tcp://192.168.3.100:26657"
    api_server_endpoint: "http://192.168.3.100:8545"
